connect:
    modules:
        todo:
            class: "Wr\\Connect\\CoreBundle\\Contao\\BackendModule\\ConnectModule\\TodoModule"
        time:
            class: "Wr\\Connect\\CoreBundle\\Contao\\BackendModule\\ConnectModule\\TimeModule"
        abo:
            class: "Wr\\Connect\\CoreBundle\\Contao\\BackendModule\\ConnectModule\\AboModule"